// ============================================================================
// Onboarding Constants
// ============================================================================

export const DIASPORA_TYPES = [
  { value: 'etudiante', label: '\u00c9tudiante' },
  { value: 'professionnelle', label: 'Professionnelle' },
  { value: 'familiale', label: 'Familiale' },
  { value: 'missionnaire', label: 'Missionnaire' },
] as const;

export const PAYS_LIST = [
  { value: 'FR', label: 'France' },
  { value: 'DE', label: 'Allemagne' },
  { value: 'BE', label: 'Belgique' },
  { value: 'CH', label: 'Suisse' },
  { value: 'GB', label: 'Royaume-Uni' },
  { value: 'US', label: '\u00c9tats-Unis' },
  { value: 'CA', label: 'Canada' },
  { value: 'IT', label: 'Italie' },
  { value: 'ES', label: 'Espagne' },
  { value: 'NL', label: 'Pays-Bas' },
  { value: 'AT', label: 'Autriche' },
  { value: 'SE', label: 'Su\u00e8de' },
  { value: 'NO', label: 'Norv\u00e8ge' },
  { value: 'DK', label: 'Danemark' },
  { value: 'PT', label: 'Portugal' },
  { value: 'IE', label: 'Irlande' },
  { value: 'LU', label: 'Luxembourg' },
  { value: 'CM', label: 'Cameroun' },
  { value: 'SN', label: 'S\u00e9n\u00e9gal' },
  { value: 'CI', label: "C\u00f4te d'Ivoire" },
  { value: 'GA', label: 'Gabon' },
  { value: 'CG', label: 'Congo' },
  { value: 'TD', label: 'Tchad' },
  { value: 'CF', label: 'R\u00e9publique centrafricaine' },
  { value: 'GQ', label: 'Guin\u00e9e \u00e9quatoriale' },
  { value: 'NG', label: 'Nig\u00e9ria' },
  { value: 'ZA', label: 'Afrique du Sud' },
  { value: 'MA', label: 'Maroc' },
  { value: 'TN', label: 'Tunisie' },
  { value: 'AE', label: '\u00c9mirats arabes unis' },
  { value: 'CN', label: 'Chine' },
  { value: 'JP', label: 'Japon' },
  { value: 'BR', label: 'Br\u00e9sil' },
  { value: 'AU', label: 'Australie' },
  { value: 'OTHER', label: 'Autre' },
] as const;

export const PAROISSES = [
  { value: 'bonanjo-douala', label: 'Paroisse de Bonanjo, Douala' },
  { value: 'ndogbati-douala', label: 'Paroisse de Ndogbati, Douala' },
  { value: 'new-bell-douala', label: 'Paroisse de New-Bell, Douala' },
  { value: 'deido-douala', label: 'Paroisse de Deido, Douala' },
  { value: 'akwa-douala', label: "Paroisse d'Akwa, Douala" },
  { value: 'bali-bamenda', label: 'Paroisse de Bali, Bamenda' },
  { value: 'mvolyé-yaounde', label: 'Paroisse de Mvoly\u00e9, Yaound\u00e9' },
  { value: 'mokolo-yaounde', label: 'Paroisse de Mokolo, Yaound\u00e9' },
  { value: 'nkongsamba', label: 'Paroisse de Nkongsamba' },
  { value: 'bafoussam', label: 'Paroisse de Bafoussam' },
  { value: 'foumban', label: 'Paroisse de Foumban' },
  { value: 'garoua', label: 'Paroisse de Garoua' },
  { value: 'maroua', label: 'Paroisse de Maroua' },
  { value: 'bertoua', label: 'Paroisse de Bertoua' },
  { value: 'ebolowa', label: "Paroisse d'Ebolowa" },
  { value: 'kribi', label: 'Paroisse de Kribi' },
  { value: 'limbe', label: 'Paroisse de Limbe' },
  { value: 'buea', label: 'Paroisse de Buea' },
  { value: 'siege-eec', label: 'Si\u00e8ge EEC, Douala' },
  { value: 'other', label: 'Autre paroisse' },
] as const;

export const MINISTERES_OPTIONS = [
  { value: 'chorale', label: 'Chorale' },
  { value: 'jeunesse', label: 'Jeunesse' },
  { value: 'diaconie', label: 'Diaconie' },
  { value: 'enseignement', label: 'Enseignement' },
  { value: 'priere', label: 'Groupe de pri\u00e8re' },
  { value: 'evangelisation', label: '\u00c9vang\u00e9lisation' },
  { value: 'louange', label: 'Louange' },
  { value: 'accueil', label: 'Accueil' },
  { value: 'medias', label: 'M\u00e9dias' },
  { value: 'femmes', label: 'Femmes chr\u00e9tiennes' },
  { value: 'hommes', label: 'Hommes chr\u00e9tiens' },
  { value: 'ecole-dimanche', label: '\u00c9cole du dimanche' },
] as const;
